export const Actions = {
    GET_ALL: "users/GET_ALL",
    LOADING_USERS: "users/LOADING_USERS",
    REMOVE: "users/REMOVE",
    REMOVE_LOADING: "users/REMOVE_LOADING",
    SET_ADMIN: "users/SET_ADMIN",
    REMOVE_ADMIN: "users/REMOVE_ADMIN",
    BLOCK_USER: "users/BLOCK_USER",
    UNLOCK_USER: "users/UNLOCK_USER",
    ADMIN_LOADING: "users/ADMIN_LOADING",
    BLOCK_LOADING: "users/BLOCK_LOADING",
    CHANGE_USER_INFO: "users/CHANGE_USER_INFO",
    CHANGE_USER_INFO_LOADING: "users/CHANGE_USER_INFO_LOADING"
}